[profile.default]
# Configuration par défaut
failure-output = "immediate-final"
fail-fast = false

[profile.ci]
# Profil spécifique pour la CI
retries = 2
failure-output = "immediate-final"
fail-fast = false

[profile.ci.junit]
path = "junit.xml"
